name: Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@v1

  init:
    needs:
      - clean
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
  test:
    needs:
      - init
    uses: ./.github/workflows/test.yml
    secrets: inherit
  todo:
    needs:
      - init
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-todo.yml@v1
    secrets: inherit
  deploy:
    needs:
#       - test
      - todo
    uses: ./.github/workflows/s3-deploy.yml
    secrets: inherit
    with:
      node-version: 18.x
      folder: out
      bucket:
      dist-id:
